services:
  # Backend API Service
  - type: web
    name: yummy-backend
    runtime: python
    region: oregon  # Choose closest to your users: oregon, ohio, virginia, frankfurt, singapore
    buildCommand: cd dashboard/backend && pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn
    startCommand: cd dashboard/backend && gunicorn -c gunicorn.conf.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PORT
        value: 8000
      # Add these environment variables in Render Dashboard:
      # - SUPABASE_URL (your Supabase project URL)
      # - SUPABASE_SERVICE_KEY (your Supabase service role key)
      # - GEMINI_API_KEY (Google Gemini API key)
      # - OPENAI_API_KEY (if using OpenAI)
      # - ANTHROPIC_API_KEY (Claude API key)
      # - GOOGLE_MAPS_API_KEY (Google Maps/Places API key)
      # - ELEVENLABS_API_KEY (for text-to-speech)
      # - TWILIO_ACCOUNT_SID (Twilio account SID)
      # - TWILIO_AUTH_TOKEN (Twilio auth token)
      # - TWILIO_PHONE_NUMBER (Twilio phone number)
      # - JWT_SECRET (for JWT token signing - generate a secure random string)
      # - FRONTEND_URL (URL of your Netlify deployment)
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: yummy-backend-disk
      mountPath: /var/data
      sizeGB: 1

